-- Sprint Comercial Hub — adicionar roles SDR/HUNTER/CLOSER/AE/CS/MANAGER/DIRECTOR
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SDR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'HUNTER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'CLOSER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'AE';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'CS';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'MANAGER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'DIRECTOR';
